### ISSUE TITLE
spm configurable mirrors

### ISSUE THREAD

**Issue by DarkSpyro003** [starlight/lux-minimal#1]
spm currently uses a hardcoded mirror in addition to the two custom package sites. It would be interesting if we could configure the "main cygwin repository" mirrors.

**Comment by isaacwhanson** [comment]
Indeed.  That is a very good suggestion.  I will do it.

**Comment by isaacwhanson** [comment]
I have added this functionality to `spm`, using the `-C` flag.  example:

  `spm -uC http://cygwin.mirrors.hoobly.com`

  will update all packages, using the supplied mirror.  `spm` will use the newly supplied mirror as the default until changed.

let me know if this doesn't work as expected.  I will close the issue for now.

**Comment by isaacwhanson** [comment]
https://github.com/starlight/lux-minimal/commit/19fed85a9ccd724d16f72d36c94a7043718ba202
